hmcts/sscs-pdf-email-common

- src/main/java/uk/gov/hmcts/reform/sscs/service/SscsPdfService.java
- src/test/java/uk/gov/hmcts/reform/sscs/service/SscsPdfServiceTest.java
made something more usable outside of library
> Sscs 4030 store doc ccd

- build.gradle
- src/main/java/uk/gov/hmcts/reform/sscs/json/RoboticsJsonValidator.java
- src/main/java/uk/gov/hmcts/reform/sscs/service/EvidenceManagementService.java
- src/main/java/uk/gov/hmcts/reform/sscs/service/PdfStoreService.java
- src/main/resources/schema/sscs-robotics.json
- src/test/java/uk/gov/hmcts/reform/sscs/json/RoboticsJsonValidatorTest.java
- src/test/java/uk/gov/hmcts/reform/sscs/schema/RoboticsSchemaTest.java
- src/test/java/uk/gov/hmcts/reform/sscs/service/EvidenceManagementServiceTest.java
- src/test/resources/schema/valid_robotics_agreed.json
This ticket is about adding DOB for both Appellant and Appointee.
> Sscs 4282 add details to schema

- build.gradle
- src/main/java/uk/gov/hmcts/reform/sscs/service/RoboticsService.java
- src/test/java/uk/gov/hmcts/reform/sscs/service/RoboticsServiceTest.java
- For Bulk Scanning, there is no SYA PDF generated
- This PR handles this scenario
> SSCS-4346 Handle empty PDF for bulk scan

- build.gradle
- src/main/java/uk/gov/hmcts/reform/sscs/service/CcdPdfService.java
- src/main/java/uk/gov/hmcts/reform/sscs/service/SscsPdfService.java
> SSCS-5231 Tweaks to SYA Report

- build.gradle
https://tools.hmcts.net/jira/browse/SSCS-5219
> Bump java logging version

- src/main/java/uk/gov/hmcts/reform/sscs/service/CcdPdfService.java
- src/test/java/uk/gov/hmcts/reform/sscs/service/CcdPdfServiceTest.java
We need access to the updated SscsCaseData once we have merged in
evidence documents.
> SSCS-3568 Additional Evidence Cover Sheet

- src/main/java/uk/gov/hmcts/reform/sscs/service/SscsGeneratePdfService.java
- src/main/resources/templates/direction_notice_letter_template.html
- src/main/resources/templates/direction_notice_letter_template_rep.html
- src/main/resources/templates/strike_out_letter_template_rep.html
Added templates for bundled letters that are sent to reps
```
[ ] Yes
[x] No
```
> Sscs 5512 rep letters

- src/main/resources/templates/strike_out_letter_template.html
- src/main/resources/templates/strike_out_letter_template_rep.html
> SSCS-5092 Send a letter when a case is struckout

- src/main/java/uk/gov/hmcts/reform/sscs/service/EmailService.java
Try and calculate the size of the email and attachments being sent. Log
the value so we can see if we have emails over 10 MB.
https://tools.hmcts.net/jira/browse/SSCS-6110
```
[ ] Yes
[X] No
```
> SSCS-6110 Add logging when sending email

- src/main/java/uk/gov/hmcts/reform/sscs/service/CcdNotificationsPdfService.java
- src/main/java/uk/gov/hmcts/reform/sscs/service/CcdPdfService.java
- src/test/java/uk/gov/hmcts/reform/sscs/service/CcdNotificationsPdfServiceTest.java
- src/test/java/uk/gov/hmcts/reform/sscs/service/CcdPdfServiceTest.java
remove pdf service client dependency from CcdPdfService.
> SSCS-6316 - remove pdf service client dependency if not needed

- src/main/java/uk/gov/hmcts/reform/sscs/service/CcdNotificationsPdfService.java
- src/test/java/uk/gov/hmcts/reform/sscs/service/CcdNotificationsPdfServiceTest.java
Store letters from gov notify in ccd
> SSCS-6389 - Store letters from gov notify in ccd

- src/main/resources/templates/appellant_appeal_template.html
> SSCS-6525 Common – SSCS1 form generation appeal reason field switch

- build.gradle
- src/main/java/uk/gov/hmcts/reform/sscs/service/CcdNotificationsPdfService.java
- src/test/java/uk/gov/hmcts/reform/sscs/service/CcdNotificationsPdfServiceTest.java
https://tools.hmcts.net/jira/browse/SSCS-7088
> SSCS-7088 Notification sent event

- src/main/java/uk/gov/hmcts/reform/sscs/service/CcdPdfService.java
- src/test/java/uk/gov/hmcts/reform/sscs/service/CcdPdfServiceTest.java
https://tools.hmcts.net/jira/browse/SSCS-6917
```
[ ] Yes
[x] No
```
> Added date

- src/main/java/uk/gov/hmcts/reform/sscs/service/EmailService.java
- src/test/java/uk/gov/hmcts/reform/sscs/service/EmailServiceTest.java
https://tools.hmcts.net/jira/browse/SSCS-6734
> SSCS-6734 Add case id for email logging

- build.gradle
> SSCS-7550: New-AirLookup

- src/main/java/uk/gov/hmcts/reform/sscs/docmosis/service/DocmosisPdfGenerationService.java
https://tools.hmcts.net/jira/browse/SSCS-7739
```
[ ] Yes
[ ] No
```
> SSCS-7739 Docmosis logging

- src/main/resources/templates/appellant_appeal_template.html
SSCS-7756 - Reasons For Appealing Switching
> SSCS-7756 - Reasons For Appealing Switching

- .github/workflows/gradle.yml
- build.gradle
SSCS-7802 - Upgrade to Java 11
> SSCS-7802 - Upgrade to Java 11

- build.gradle
SSCS-7309 - Set 'Previous State' field when case moves to dormant
> SSCS-7309 - Set 'Previous State' field when case moves to dormant

- build.gradle
> Wla 698 interloc

- build.gradle
> SSCS-7789 upgrade common

- build.gradle
- src/main/java/uk/gov/hmcts/reform/sscs/service/CcdNotificationsPdfService.java
- src/test/java/uk/gov/hmcts/reform/sscs/service/CcdNotificationsPdfServiceTest.java
https://tools.hmcts.net/jira/browse/SSCS-8495
Merge in letter onto case
```
[ ] Yes
[x] No
```
> Sscs 8495 reasonable adjustments

- build.gradle
SSCS-8750 - Dwp Document sorting
> SSCS-8750 - Dwp Document sorting

- src/main/java/uk/gov/hmcts/reform/sscs/service/conversion/RtfConverter.java
- src/test/java/uk/gov/hmcts/reform/sscs/service/conversion/RtfConverterTest.java
- src/test/java/uk/gov/hmcts/reform/sscs/service/conversion/WordDocumentConverterTest.java
- src/test/resources/Evidence.rtf
https://tools.hmcts.net/jira/browse/SSCS-8661
Added rtf file type to conversions
```
[ ] Yes
[x] No
```
> sscs 8661 handles RTF files when uploaded

- build.gradle
https://tools.hmcts.net/jira/browse/SSCS-8861
> Bump common

- .github/workflows/gradle.yml
- jitpack.yml
- Add jitpack custom commands
- Remove bintray upload from pipeline
> DTSPO-1792 jitpack publish

- .github/workflows/jitpack_build.yml
- Force jitpack to build when code is tagged
> DTSPO-1792 - add jitpack build workflow

- build.gradle
# SSCS-9043 - build common libraries
- renamed group
> SSCS-9043 - build common libraries

- jitpack_build.yml
> Improve Jitpack Script

- .github/workflows/jitpack_build.yml
- Update jitpack script to wait 6 times before failing and increase sleep to 30 seconds
```
[ ] Yes
[x] No
```
> Jitpack script update

- build.gradle
https://tools.hmcts.net/jira/browse/SSCS-9066
Remove bintray repo
```
[ ] Yes
[x] No
```
> sscs 9066 remove reference to bintray

- src/main/java/uk/gov/hmcts/reform/sscs/helper/PdfHelper.java
- src/test/java/uk/gov/hmcts/reform/sscs/helper/PdfHelperTest.java
> SSCS-9378: Resize documents issue seen on representative documents

- build.gradle
- src/main/java/uk/gov/hmcts/reform/sscs/service/EvidenceManagementSecureDocStoreService.java
- src/main/java/uk/gov/hmcts/reform/sscs/service/PdfStoreService.java
- src/test/java/uk/gov/hmcts/reform/sscs/service/EvidenceManagementSecureDocStoreServiceTest.java
- src/test/java/uk/gov/hmcts/reform/sscs/service/PdfStoreServiceTest.java
> SSCS-9362 - Secure doc store

- src/main/java/uk/gov/hmcts/reform/sscs/service/EvidenceManagementSecureDocStoreService.java
- src/main/java/uk/gov/hmcts/reform/sscs/service/PdfStoreService.java
- src/test/java/uk/gov/hmcts/reform/sscs/service/EvidenceManagementSecureDocStoreServiceTest.java
https://tools.hmcts.net/jira/browse/SSCS-8708
Download secure docstore
```
[ ] Yes
[x] No
```
> Sscs 8708 download secure docstore

- build.gradle
SSCS-9420 - Update doc store client
> SSCS-9420 - Update doc store client

- src/main/java/uk/gov/hmcts/reform/sscs/service/CcdPdfService.java
- src/main/java/uk/gov/hmcts/reform/sscs/service/PdfStoreService.java
- src/test/java/uk/gov/hmcts/reform/sscs/service/CcdPdfServiceTest.java
- src/test/java/uk/gov/hmcts/reform/sscs/service/PdfStoreServiceTest.java
SSCS-9335 - Time set to 12am for Statement upload
> SSCS-9335 - Time set to 12am for Statement upload

- src/main/java/uk/gov/hmcts/reform/sscs/service/PdfStoreService.java
Change for release of secure docstore to stop expected error messages
```
[ ] Yes
[x] No
```
> change log error to info

- build.gradle
- src/main/java/uk/gov/hmcts/reform/sscs/service/PdfStoreService.java
Fix for dependency
```
[ ] Yes
[x] No
```
> Release secure docstore logging

- build.gradle
- src/main/java/uk/gov/hmcts/reform/sscs/domain/UpdateDocParams.java
- src/main/java/uk/gov/hmcts/reform/sscs/service/CcdPdfService.java
- src/main/java/uk/gov/hmcts/reform/sscs/service/PdfStoreService.java
- src/test/java/uk/gov/hmcts/reform/sscs/service/CcdPdfServiceTest.java
SSCS-9825 - MYA: Upload Evidence / Upload Audio Video Evidence
> SSCS-9825 - MYA: Upload Evidence / Upload Audio Video Evidence

- build.gradle
- src/main/java/uk/gov/hmcts/reform/sscs/service/CcdNotificationsPdfService.java
- src/test/java/uk/gov/hmcts/reform/sscs/service/CcdNotificationsPdfServiceTest.java
https://tools.hmcts.net/jira/browse/SSCS-9730
> SSCS-9730 Other party reasonable adjustments

- build.gradle
https://tools.hmcts.net/jira/browse/SSCS-10166
poi version is updated as the security vulnerabilities they have are preventing feature developments
```
[X ] Yes
[ ] No
```
> SSCS-10166-Upgrade/Fix poi and commons-beanutils vulnerabilities

- build.gradle
> SSCS-10479 Remove jCenter.

- build.gradle
https://tools.hmcts.net/jira/browse/SSCS-10445
```
[ ] Yes
[x] No
```
> SSCS-10445 Commons Bump

- build.gradle
https://tools.hmcts.net/jira/browse/SSCS-10178
```
[ ] Yes
[x] No
```
> SSCS-10178 Commons Bump

- build.gradle
https://tools.hmcts.net/jira/browse/SSCS-9874
```
[ ] Yes
[ ] No
```
> SSCS-9874-common-version-update

- build.gradle
https://tools.hmcts.net/jira/browse/SSCS-10818
```
[ ] Yes
[x] No
```
> SSCS-10818 Commons Bump

- build.gradle
https://tools.hmcts.net/jira/browse/SSCS-10882
```
[ ] Yes
[x] No
```
> SSCS-10882 Fixing Conflicting IDs

- build.gradle
commons bump
SSCS-10895
commons bump
```
[ ] Yes
[x] No
```
> Commons bump for SSCS-10895

- build.gradle
- config/owasp/suppressions.xml
> suppress and upgrade

- build.gradle
> renovate 23-03-23

- build.gradle
- src/test/java/uk/gov/hmcts/reform/sscs/domain/email/EmailAttachmentTest.java
> renovate 23-04-26

- config/owasp/suppressions.xml
CVE Fix
```
[ ] Yes
[x] No
```
> CVEFix.06.06.2023

- build.gradle
- config/owasp/suppressions.xml
> renovate 2023-07-03

- build.gradle
- gradle/wrapper/gradle-wrapper.properties
> renovate 2023-07-25

- build.gradle
- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/SSCS-11717
SSCS-11717 - Java 17
```
[ ] Yes
[x] No
```
> SSCS-11717 - Upgrade to Java 17

- src/main/java/uk/gov/hmcts/reform/sscs/service/CcdNotificationsPdfService.java
https://tools.hmcts.net/jira/browse/SSCS-12185
Made generic method to store notifications
> Made generic method to store notifications

- build.gradle
- config/owasp/suppressions.xml
- src/main/java/uk/gov/hmcts/reform/sscs/service/CcdNotificationsPdfService.java
- src/test/java/uk/gov/hmcts/reform/sscs/service/CcdNotificationsPdfServiceTest.java
https://tools.hmcts.net/jira/browse/SSCSSI-6
> Added new helper method which retrieves data from CCD DB and updates correspondence instead of in memory copy of ccd data

- config/owasp/suppressions.xml
Update pdf commons suppressions file
> SSCSCI - Update suppressions

- build.gradle
- src/main/java/uk/gov/hmcts/reform/sscs/service/CcdNotificationsPdfService.java
- src/test/java/uk/gov/hmcts/reform/sscs/service/CcdNotificationsPdfServiceTest.java
https://tools.hmcts.net/jira/browse/SSCSSI-161
> Bump sscs-common version, change updateCaseV2 calls

- build.gradle
- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/SSCSCI-957
Dependency check bump to latest version (10.0.3)
> SSCSCI-957 dependency check bump

- build.gradle
- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/SSCSSI-336
Updated sscs-common
- [ X] commit messages are meaningful and follow good commit message guidelines
> SSCSSI-336: Updated sscs-common

- build.gradle
- See [SSCSCI-1028](https://tools.hmcts.net/jira/browse/SSCSCI-1028)
- Upgrade common lib to 5.12.2, with fix for language reference concatenation
> upgrade common lib to 5.12.2

- build.gradle
> SSCSCI: update commons

- build.gradle
- config/owasp/suppressions.xml
See [SSCSCI-995](https://tools.hmcts.net/jira/browse/SSCSCI-995)
- Updated sscs-common
- Updated jackson-databind from 2.15.2 to 2.17.2
- Added variable for versions in gradle
> SSCSCI-995-jackson-databind-bump

- build.gradle
Jira link
See [SSCSCI-1406](https://tools.hmcts.net/jira/browse/SSCSCI-1406)
Change description
Latest commons change fixes a isIbcCase check when on create case mid event
> Bumping sscs commons version

- build.gradle
https://tools.hmcts.net/jira/browse/SSCSSI-247
- [x ] commit messages are meaningful and follow good commit message guidelines
> SSCSSI-247: Updated sscs-commons

- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/SSCSSI-247
Updated suppressions
- [x ] commit messages are meaningful and follow good commit message guidelines
> SSCSSI-247: Updated suppressions

- build.gradle
- config/owasp/suppressions.xml
See [SSCSCI-1397](https://tools.hmcts.net/jira/browse/SSCSCI-1397)
> commons bump

- build.gradle
- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/SSCSSI-339
Updated sscs-common
- [ x] commit messages are meaningful and follow good commit message guidelines
> SSCSSI-339: Updated sscs-common

- config/owasp/suppressions.xml
- src/main/java/uk/gov/hmcts/reform/sscs/service/CcdNotificationsPdfService.java
See [SSCSCI-1508](https://tools.hmcts.net/jira/browse/SSCSCI-1508)
generalising notifications by removing dwp at start of fileName
> SSCSCI-1508
